/**
 * chau7_terminal.h - C FFI Interface for Chau7 Terminal Emulator
 *
 * Auto-generated by cbindgen. Do not edit directly.
 */

#ifndef CHAU7_TERMINAL_H
#define CHAU7_TERMINAL_H

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/*
 Flags for cell attributes (bold, italic, underline, etc.)
 */
#define CELL_FLAG_BOLD (1 << 0)

#define CELL_FLAG_ITALIC (1 << 1)

#define CELL_FLAG_UNDERLINE (1 << 2)

#define CELL_FLAG_STRIKETHROUGH (1 << 3)

#define CELL_FLAG_INVERSE (1 << 4)

#define CELL_FLAG_DIM (1 << 5)

#define CELL_FLAG_HIDDEN (1 << 6)

/*
 Underline style variants (stored in CellData._pad byte, formerly unused).
 0 = no underline (or simple single), 1 = single, 2 = double, 3 = curl, 4 = dotted, 5 = dashed.
 */
#define UNDERLINE_SINGLE 1

#define UNDERLINE_DOUBLE 2

#define UNDERLINE_CURL 3

#define UNDERLINE_DOTTED 4

#define UNDERLINE_DASHED 5

/*
 The main terminal emulator structure.

 # Lock Ordering

 Acquire locks in ascending order to prevent deadlocks:

 1. `pty_handle`           (Mutex)  — PTY writer for input/resize
 2. `term`                 (Mutex)  — alacritty terminal state
 3. `processor`            (Mutex)  — VTE processor (always acquired with #2)
 4. `theme_colors`         (RwLock) — theme for rendering (read-heavy)
 5. `last_output`          (Mutex)  — raw output buffer
 6. `pending_title`        (Mutex)  — title change
 7. `pending_exit_code`    (Mutex)  — exit code
 8. `graphics_interceptor` (Mutex)  — image pre-filter
 9. `image_store`          (Mutex)  — decoded images
 10. `child`               (Mutex)  — child process (Drop only)
 */
typedef struct Chau7Terminal Chau7Terminal;

/*
 C-compatible cell data for a single terminal cell
 */
typedef struct CellData {
    /*
     Unicode codepoint of the character
     */
    uint32_t character;
    /*
     Foreground color RGB
     */
    uint8_t fg_r;
    uint8_t fg_g;
    uint8_t fg_b;
    /*
     Background color RGB
     */
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
    /*
     Cell attribute flags (bold, italic, underline, etc.)
     */
    uint8_t flags;
    /*
     Padding byte for natural alignment of link_id
     */
    uint8_t _pad;
    /*
     Hyperlink ID (OSC 8). 0 = no link. Use chau7_terminal_get_link_url() to resolve.
     */
    uint16_t link_id;
} CellData;

/*
 C-compatible grid snapshot containing all cell data
 */
typedef struct GridSnapshot {
    /*
     Pointer to array of CellData (cols * rows elements)
     */
    struct CellData *cells;
    /*
     Number of columns
     */
    uint16_t cols;
    /*
     Number of visible rows
     */
    uint16_t rows;
    /*
     Number of scrollback rows available
     */
    uint32_t scrollback_rows;
    /*
     Current display offset (scroll position)
     */
    uint32_t display_offset;
    /*
     Capacity of cells array (for proper deallocation)
     */
    size_t capacity;
} GridSnapshot;

/*
 Pool statistics for debugging
 */
typedef struct PoolStats {
    uint64_t acquired;
    uint64_t returned;
    uint64_t allocated;
    uint64_t pooled;
} PoolStats;

/*
 Debug state snapshot for inspection
 */
typedef struct DebugState {
    /*
     Terminal ID
     */
    uint64_t id;
    /*
     Columns
     */
    uint16_t cols;
    /*
     Rows
     */
    uint16_t rows;
    /*
     History size (scrollback lines)
     */
    uint32_t history_size;
    /*
     Current display offset
     */
    uint32_t display_offset;
    /*
     Cursor column
     */
    uint16_t cursor_col;
    /*
     Cursor row
     */
    uint16_t cursor_row;
    /*
     Total bytes sent
     */
    uint64_t bytes_sent;
    /*
     Total bytes received
     */
    uint64_t bytes_received;
    /*
     Uptime in milliseconds
     */
    uint64_t uptime_ms;
    /*
     Is grid dirty (u8 for FFI safety: 0 = false, 1 = true)
     */
    uint8_t grid_dirty;
    /*
     Is running (u8 for FFI safety)
     */
    uint8_t running;
    /*
     Has selection (u8 for FFI safety)
     */
    uint8_t has_selection;
    /*
     Mouse mode bitmask
     */
    uint32_t mouse_mode;
    /*
     Is bracketed paste mode (u8 for FFI safety)
     */
    uint8_t bracketed_paste;
    /*
     Is application cursor mode (u8 for FFI safety)
     */
    uint8_t app_cursor;
    /*
     Poll count
     */
    uint64_t poll_count;
    /*
     Average poll time in microseconds
     */
    uint64_t avg_poll_time_us;
    /*
     Max poll time in microseconds
     */
    uint64_t max_poll_time_us;
    /*
     Average grid snapshot time in microseconds
     */
    uint64_t avg_grid_snapshot_time_us;
    /*
     Max grid snapshot time in microseconds
     */
    uint64_t max_grid_snapshot_time_us;
    /*
     Activity level percentage (0-100)
     */
    uint8_t activity_percent;
    /*
     Number of idle polls
     */
    uint64_t idle_polls;
    /*
     Average batch size in bytes
     */
    uint64_t avg_batch_size;
    /*
     Dirty row count (for partial updates)
     */
    uint32_t dirty_row_count;
} DebugState;

/*
 C-compatible image data for FFI transfer to Swift.
 Fields ordered by descending alignment to minimize padding.
 */
typedef struct FFIImageData {
    /*
     Image ID (unique per terminal instance).
     */
    uint64_t id;
    /*
     Pointer to raw image data (base64 for iTerm2, raw bytes for Sixel/Kitty).
     */
    uint8_t *data;
    /*
     Length of the data buffer.
     */
    size_t data_len;
    /*
     Capacity of the data buffer (must match original Vec allocation for safe free).
     */
    size_t data_capacity;
    /*
     Cursor row when image was received (grid-relative).
     */
    int32_t anchor_row;
    /*
     Cursor column when image was received.
     */
    uint16_t anchor_col;
    /*
     Protocol that produced this image (0=iTerm2, 1=Sixel, 2=Kitty).
     */
    uint8_t protocol;
} FFIImageData;

/*
 C-compatible array of pending images.
 */
typedef struct FFIImageArray {
    /*
     Pointer to array of FFIImageData structs.
     */
    struct FFIImageData *images;
    /*
     Number of images in the array.
     */
    size_t count;
    /*
     Capacity of the images array (must match original Vec allocation for safe free).
     */
    size_t capacity;
} FFIImageArray;

/*
 Create a new terminal with the specified dimensions and shell

 # Safety
 - `shell` must be a valid null-terminated C string, or null for default shell
 - Returns null on failure
 */
struct Chau7Terminal *chau7_terminal_create(uint16_t cols, uint16_t rows, const char *shell);

/*
 Create a new terminal with environment variables

 # Safety
 - `shell` must be a valid null-terminated C string, or null for default shell
 - `env_keys` and `env_values` must be arrays of valid null-terminated C strings
 - `env_count` must be the length of both arrays
 - Returns null on failure
 */
struct Chau7Terminal *chau7_terminal_create_with_env(uint16_t cols,
                                                     uint16_t rows,
                                                     const char *shell,
                                                     const char *const *env_keys,
                                                     const char *const *env_values,
                                                     size_t env_count);

/*
 Destroy a terminal instance

 # Safety
 - `term` must be a valid pointer returned by `chau7_terminal_create`
 */
void chau7_terminal_destroy(struct Chau7Terminal *term);

/*
 Send raw bytes to the PTY (user input)

 # Safety
 - `term` must be a valid pointer
 - `data` must be a valid pointer to at least `len` bytes
 */
void chau7_terminal_send_bytes(struct Chau7Terminal *term, const uint8_t *data, size_t len);

/*
 Send a null-terminated string to the PTY

 # Safety
 - `term` must be a valid pointer
 - `text` must be a valid null-terminated C string
 */
void chau7_terminal_send_text(struct Chau7Terminal *term, const char *text);

/*
 Resize the terminal

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_resize(struct Chau7Terminal *term, uint16_t cols, uint16_t rows);

/*
 Get a snapshot of the current grid state

 # Safety
 - `term` must be a valid pointer
 - The returned GridSnapshot must be freed with `chau7_terminal_free_grid`
 */
struct GridSnapshot *chau7_terminal_get_grid(struct Chau7Terminal *term);

/*
 Free a grid snapshot

 # Safety
 - `grid` must be a valid pointer returned by `chau7_terminal_get_grid`
 */
void chau7_terminal_free_grid(struct GridSnapshot *grid);

/*
 Get cell buffer pool statistics
 */
struct PoolStats chau7_terminal_pool_stats(void);

/*
 Get current scroll position (0.0 = bottom, 1.0 = top of history)

 # Safety
 - `term` must be a valid pointer
 */
double chau7_terminal_scroll_position(struct Chau7Terminal *term);

/*
 Scroll to a normalized position (0.0 = bottom, 1.0 = top of history)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_scroll_to(struct Chau7Terminal *term, double position);

/*
 Scroll by a number of lines (positive = up/back, negative = down/forward)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_scroll_lines(struct Chau7Terminal *term, int32_t lines);

/*
 Get currently selected text

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_selection_text(struct Chau7Terminal *term);

/*
 Clear any active selection

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_clear(struct Chau7Terminal *term);

/*
 Start a new selection at the given position

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_start(struct Chau7Terminal *term,
                                    int32_t col,
                                    int32_t row,
                                    uint8_t selection_type);

/*
 Update the current selection to extend to the given position

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_update(struct Chau7Terminal *term, int32_t col, int32_t row);

/*
 Select all content (screen + scrollback)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_all(struct Chau7Terminal *term);

/*
 Free a string returned by the library

 # Safety
 - `s` must be a valid pointer returned by `chau7_terminal_selection_text` or similar
 */
void chau7_terminal_free_string(char *s);

/*
 Get the text of a specific line in the terminal grid

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_line_text(struct Chau7Terminal *term, int32_t row);

/*
 Get cursor position

 # Safety
 - `term` must be a valid pointer
 - `col` and `row` must be valid pointers to u16, or null
 */
void chau7_terminal_cursor_position(struct Chau7Terminal *term, uint16_t *col, uint16_t *row);

/*
 Poll for new data from PTY and process it

 Returns true if the grid has changed and needs to be redrawn

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_poll(struct Chau7Terminal *term, uint32_t timeout_ms);

/*
 Get raw output bytes from the last poll

 # Safety
 - `term` must be a valid pointer
 - `out_len` must be a valid pointer to a usize
 - The returned pointer must be freed via chau7_terminal_free_output
 */
uint8_t *chau7_terminal_get_last_output(struct Chau7Terminal *term, size_t *out_len);

/*
 Inject output bytes directly into the terminal (without sending to PTY)

 # Safety
 - `term` must be a valid pointer
 - `data` must be a valid pointer to at least `len` bytes (unless `len` is 0)
 */
void chau7_terminal_inject_output(struct Chau7Terminal *term, const uint8_t *data, size_t len);

/*
 Free output bytes returned by chau7_terminal_get_last_output

 # Safety
 - `data` must be a pointer returned by `chau7_terminal_get_last_output`
 - `len` must be the length returned with that pointer
 */
void chau7_terminal_free_output(uint8_t *data, size_t len);

/*
 Set theme colors for rendering

 # Safety
 - `term` must be a valid pointer
 - `palette` must be a valid pointer to an array of 48 bytes (16 RGB triplets)
 */
void chau7_terminal_set_colors(struct Chau7Terminal *term,
                               uint8_t fg_r,
                               uint8_t fg_g,
                               uint8_t fg_b,
                               uint8_t bg_r,
                               uint8_t bg_g,
                               uint8_t bg_b,
                               uint8_t cursor_r,
                               uint8_t cursor_g,
                               uint8_t cursor_b,
                               const uint8_t *palette);

/*
 Clear the scrollback history buffer

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_clear_scrollback(struct Chau7Terminal *term);

/*
 Set the scrollback buffer size (number of lines)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_set_scrollback_size(struct Chau7Terminal *term, uint32_t lines);

/*
 Get the current display offset (scroll position in lines)

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_display_offset(struct Chau7Terminal *term);

/*
 Check if bracketed paste mode is enabled

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_bracketed_paste_mode(struct Chau7Terminal *term);

/*
 Check if application cursor mode (DECCKM) is enabled

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_application_cursor_mode(struct Chau7Terminal *term);

/*
 Check if a bell event has occurred since the last check

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_check_bell(struct Chau7Terminal *term);

/*
 Get the current mouse mode as a bitmask (alias for chau7_terminal_mouse_mode)

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_get_mouse_mode(struct Chau7Terminal *term);

/*
 Check if any mouse tracking mode is active

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_mouse_reporting_active(struct Chau7Terminal *term);

/*
 Get the shell process ID

 # Safety
 - `term` must be a valid pointer
 */
uint64_t chau7_terminal_get_shell_pid(struct Chau7Terminal *term);

/*
 Get a comprehensive debug state snapshot

 # Safety
 - `term` must be a valid pointer
 - The returned pointer must be freed with `chau7_terminal_free_debug_state`
 */
struct DebugState *chau7_terminal_get_debug_state(struct Chau7Terminal *term);

/*
 Free a debug state

 # Safety
 - `state` must be a valid pointer returned by `chau7_terminal_get_debug_state`
 */
void chau7_terminal_free_debug_state(struct DebugState *state);

/*
 Get the full buffer text (visible + scrollback) for debugging

 # Safety
 - `term` must be a valid pointer
 - The returned pointer must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_full_buffer_text(struct Chau7Terminal *term);

/*
 Reset performance metrics

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_reset_metrics(struct Chau7Terminal *term);

/*
 Get current activity level (0-100)

 # Safety
 - `term` must be a valid pointer
 */
uint8_t chau7_terminal_activity_level(struct Chau7Terminal *term);

/*
 Check if poll should be skipped (power saving)

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_should_skip_poll(struct Chau7Terminal *term);

/*
 Get count of dirty rows

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_dirty_row_count(struct Chau7Terminal *term);

/*
 Clear dirty row tracking

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_clear_dirty_rows(struct Chau7Terminal *term);

/*
 Get pending title change from OSC 0/1/2 escape sequences

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_pending_title(struct Chau7Terminal *term);

/*
 Get pending child exit code

 # Safety
 - `term` must be a valid pointer
 */
int32_t chau7_terminal_get_pending_exit_code(struct Chau7Terminal *term);

/*
 Check if the PTY has closed

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_pty_closed(struct Chau7Terminal *term);

/*
 Check if the PTY has echo disabled (password mode)

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_echo_disabled(struct Chau7Terminal *term);

/*
 Get the URL for a hyperlink ID from the most recent grid snapshot.
 Returns null if the ID is 0 or invalid.

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_link_url(struct Chau7Terminal *term, uint16_t link_id);

/*
 Get pending clipboard store text (OSC 52 write to system clipboard).
 Returns a C string that must be freed with `chau7_terminal_free_string`,
 or null if no clipboard store is pending.

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_pending_clipboard(struct Chau7Terminal *term);

/*
 Check if the terminal has a pending clipboard load request (OSC 52 read).

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_has_clipboard_request(struct Chau7Terminal *term);

/*
 Respond to a pending clipboard load request by providing the current system clipboard text.
 The text is wrapped in the proper OSC 52 response sequence and written to the PTY.

 # Safety
 - `term` must be a valid pointer
 - `text` must be a valid null-terminated C string
 */
void chau7_terminal_respond_clipboard(struct Chau7Terminal *term, const char *text);

/*
 Get pending images from the graphics interceptor

 # Safety
 - `term` must be a valid pointer
 - The returned FFIImageArray must be freed with `chau7_terminal_free_images`
 */
struct FFIImageArray *chau7_terminal_get_pending_images(struct Chau7Terminal *term);

/*
 Free an FFIImageArray returned by chau7_terminal_get_pending_images

 # Safety
 - `array` must be a valid pointer returned by `chau7_terminal_get_pending_images`
 */
void chau7_terminal_free_images(struct FFIImageArray *array);

/*
 Set which image protocols the graphics interceptor should detect

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_set_image_protocols(struct Chau7Terminal *term,
                                        bool sixel,
                                        bool kitty,
                                        bool iterm2);

/*
 Check if there are pending images

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_has_pending_images(struct Chau7Terminal *term);

#endif  /* CHAU7_TERMINAL_H */
