/**
 * chau7_terminal.h - C FFI Interface for Chau7 Terminal Emulator
 *
 * Auto-generated by cbindgen. Do not edit directly.
 */

#ifndef CHAU7_TERMINAL_H
#define CHAU7_TERMINAL_H

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/*
 Flags for cell attributes (bold, italic, underline, etc.)
 */
#define CELL_FLAG_BOLD (1 << 0)

#define CELL_FLAG_ITALIC (1 << 1)

#define CELL_FLAG_UNDERLINE (1 << 2)

#define CELL_FLAG_STRIKETHROUGH (1 << 3)

#define CELL_FLAG_INVERSE (1 << 4)

#define CELL_FLAG_DIM (1 << 5)

#define CELL_FLAG_HIDDEN (1 << 6)

/*
 The main terminal emulator structure
 */
typedef struct Chau7Terminal Chau7Terminal;

/*
 C-compatible cell data for a single terminal cell
 */
typedef struct CellData {
    /*
     Unicode codepoint of the character
     */
    uint32_t character;
    /*
     Foreground color RGB
     */
    uint8_t fg_r;
    uint8_t fg_g;
    uint8_t fg_b;
    /*
     Background color RGB
     */
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
    /*
     Cell attribute flags (bold, italic, underline, etc.)
     */
    uint8_t flags;
} CellData;

/*
 C-compatible grid snapshot containing all cell data
 */
typedef struct GridSnapshot {
    /*
     Pointer to array of CellData (cols * rows elements)
     */
    struct CellData *cells;
    /*
     Number of columns
     */
    uint16_t cols;
    /*
     Number of visible rows
     */
    uint16_t rows;
    /*
     Number of scrollback rows available
     */
    uint32_t scrollback_rows;
    /*
     Current display offset (scroll position)
     */
    uint32_t display_offset;
    /*
     Capacity of cells array (for proper deallocation)
     */
    size_t capacity;
} GridSnapshot;

/*
 Pool statistics returned by chau7_terminal_pool_stats
 */
typedef struct PoolStats {
    uint64_t acquired;
    uint64_t returned;
    uint64_t allocated;
    uint64_t pooled;
} PoolStats;

/*
 Debug state snapshot for inspection
 */
typedef struct DebugState {
    /*
     Terminal ID
     */
    uint64_t id;
    /*
     Columns
     */
    uint16_t cols;
    /*
     Rows
     */
    uint16_t rows;
    /*
     History size (scrollback lines)
     */
    uint32_t history_size;
    /*
     Current display offset
     */
    uint32_t display_offset;
    /*
     Cursor column
     */
    uint16_t cursor_col;
    /*
     Cursor row
     */
    uint16_t cursor_row;
    /*
     Total bytes sent
     */
    uint64_t bytes_sent;
    /*
     Total bytes received
     */
    uint64_t bytes_received;
    /*
     Uptime in milliseconds
     */
    uint64_t uptime_ms;
    /*
     Is grid dirty (u8 for FFI safety: 0 = false, 1 = true)
     */
    uint8_t grid_dirty;
    /*
     Is running (u8 for FFI safety)
     */
    uint8_t running;
    /*
     Has selection (u8 for FFI safety)
     */
    uint8_t has_selection;
    /*
     Mouse mode bitmask
     */
    uint32_t mouse_mode;
    /*
     Is bracketed paste mode (u8 for FFI safety)
     */
    uint8_t bracketed_paste;
    /*
     Is application cursor mode (u8 for FFI safety)
     */
    uint8_t app_cursor;
    /*
     Poll count
     */
    uint64_t poll_count;
    /*
     Average poll time in microseconds
     */
    uint64_t avg_poll_time_us;
    /*
     Max poll time in microseconds
     */
    uint64_t max_poll_time_us;
    /*
     Average grid snapshot time in microseconds
     */
    uint64_t avg_grid_snapshot_time_us;
    /*
     Max grid snapshot time in microseconds
     */
    uint64_t max_grid_snapshot_time_us;
    /*
     Activity level percentage (0-100)
     */
    uint8_t activity_percent;
    /*
     Number of idle polls
     */
    uint64_t idle_polls;
    /*
     Average batch size in bytes
     */
    uint64_t avg_batch_size;
    /*
     Dirty row count (for partial updates)
     */
    uint32_t dirty_row_count;
} DebugState;

/*
 Create a new terminal with the specified dimensions and shell

 # Safety
 - `shell` must be a valid null-terminated C string, or null for default shell
 - Returns null on failure
 */
struct Chau7Terminal *chau7_terminal_create(uint16_t cols, uint16_t rows, const char *shell);

/*
 Create a new terminal with environment variables

 # Safety
 - `shell` must be a valid null-terminated C string, or null for default shell
 - `env_keys` and `env_values` must be arrays of valid null-terminated C strings
 - `env_count` must be the length of both arrays
 - Returns null on failure
 */
struct Chau7Terminal *chau7_terminal_create_with_env(uint16_t cols,
                                                     uint16_t rows,
                                                     const char *shell,
                                                     const char *const *env_keys,
                                                     const char *const *env_values,
                                                     size_t env_count);

/*
 Destroy a terminal instance

 # Safety
 - `term` must be a valid pointer returned by `chau7_terminal_create`
 - The pointer must not be used after this call
 */
void chau7_terminal_destroy(struct Chau7Terminal *term);

/*
 Send raw bytes to the PTY (user input)

 # Safety
 - `term` must be a valid pointer
 - `data` must be a valid pointer to at least `len` bytes
 */
void chau7_terminal_send_bytes(struct Chau7Terminal *term, const uint8_t *data, size_t len);

/*
 Send a null-terminated string to the PTY

 # Safety
 - `term` must be a valid pointer
 - `text` must be a valid null-terminated C string
 */
void chau7_terminal_send_text(struct Chau7Terminal *term, const char *text);

/*
 Resize the terminal

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_resize(struct Chau7Terminal *term, uint16_t cols, uint16_t rows);

/*
 Get a snapshot of the current grid state

 # Safety
 - `term` must be a valid pointer
 - Returns null on failure
 - The returned GridSnapshot must be freed with `chau7_terminal_free_grid`
 */
struct GridSnapshot *chau7_terminal_get_grid(struct Chau7Terminal *term);

/*
 Free a grid snapshot

 # Safety
 - `grid` must be a valid pointer returned by `chau7_terminal_get_grid`
 - The pointer must not be used after this call
 */
void chau7_terminal_free_grid(struct GridSnapshot *grid);

/*
 Get cell buffer pool statistics for debugging/monitoring
 Returns: (acquired, returned, allocated, pooled)
 - acquired: total buffers acquired from pool
 - returned: total buffers returned to pool
 - allocated: new allocations (pool misses)
 - pooled: current buffers in pool
 */
struct PoolStats chau7_terminal_pool_stats(void);

/*
 Get current scroll position (0.0 = bottom, 1.0 = top of history)

 # Safety
 - `term` must be a valid pointer
 */
double chau7_terminal_scroll_position(struct Chau7Terminal *term);

/*
 Scroll to a normalized position (0.0 = bottom, 1.0 = top of history)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_scroll_to(struct Chau7Terminal *term, double position);

/*
 Scroll by a number of lines (positive = up/back, negative = down/forward)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_scroll_lines(struct Chau7Terminal *term, int32_t lines);

/*
 Get currently selected text

 # Safety
 - `term` must be a valid pointer
 - Returns null if no selection or on failure
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_selection_text(struct Chau7Terminal *term);

/*
 Clear any active selection

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_clear(struct Chau7Terminal *term);

/*
 Start a new selection at the given position

 # Arguments
 - `col`: Column position (0-indexed)
 - `row`: Row position (can be negative for scrollback)
 - `selection_type`: 0 = Simple (character), 1 = Block, 2 = Semantic (word), 3 = Lines

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_start(struct Chau7Terminal *term,
                                    int32_t col,
                                    int32_t row,
                                    uint8_t selection_type);

/*
 Update the current selection to extend to the given position

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_update(struct Chau7Terminal *term, int32_t col, int32_t row);

/*
 Select all content (screen + scrollback)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_selection_all(struct Chau7Terminal *term);

/*
 Free a string returned by the library

 # Safety
 - `s` must be a valid pointer returned by `chau7_terminal_selection_text` or similar
 - The pointer must not be used after this call
 */
void chau7_terminal_free_string(char *s);

/*
 Get the text of a specific line in the terminal grid.

 The `row` index is in grid coordinates where 0 is the top of the visible
 viewport. Negative rows refer to scrollback when available.

 Returns a null-terminated UTF-8 string. The caller must free it with
 `chau7_terminal_free_string`.

 # Safety
 - `term` must be a valid pointer
 */
char *chau7_terminal_get_line_text(struct Chau7Terminal *term, int32_t row);

/*
 Get cursor position

 # Safety
 - `term` must be a valid pointer
 - `col` and `row` must be valid pointers to u16, or null
 */
void chau7_terminal_cursor_position(struct Chau7Terminal *term, uint16_t *col, uint16_t *row);

/*
 Poll for new data from PTY and process it

 Returns true if the grid has changed and needs to be redrawn

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_poll(struct Chau7Terminal *term, uint32_t timeout_ms);

/*
 Get raw output bytes from the last poll.
 Returns a pointer to the byte data and the length.
 Each call returns a new allocation that must be freed via chau7_terminal_free_output.

 # Safety
 - `term` must be a valid pointer
 - `out_len` must be a valid pointer to a usize
 - The returned pointer must be freed via chau7_terminal_free_output
 - Returns null if no output is available
 */
uint8_t *chau7_terminal_get_last_output(struct Chau7Terminal *term, size_t *out_len);

/*
 Inject output bytes directly into the terminal (without sending to PTY).
 This is used for UI-only content like the power user tip header.

 # Safety
 - `term` must be a valid pointer returned by `chau7_terminal_create`
 - `data` must be a valid pointer to at least `len` bytes (unless `len` is 0)
 */
void chau7_terminal_inject_output(struct Chau7Terminal *term, const uint8_t *data, size_t len);

/*
 Free output bytes returned by chau7_terminal_get_last_output

 # Safety
 - `data` must be a pointer returned by `chau7_terminal_get_last_output`
 - `len` must be the length returned with that pointer
 - The pointer must not be used after this call
 */
void chau7_terminal_free_output(uint8_t *data, size_t len);

/*
 Set theme colors for rendering

 # Safety
 - `term` must be a valid pointer
 - `palette` must be a valid pointer to an array of 48 bytes (16 RGB triplets)
 */
void chau7_terminal_set_colors(struct Chau7Terminal *term,
                               uint8_t fg_r,
                               uint8_t fg_g,
                               uint8_t fg_b,
                               uint8_t bg_r,
                               uint8_t bg_g,
                               uint8_t bg_b,
                               uint8_t cursor_r,
                               uint8_t cursor_g,
                               uint8_t cursor_b,
                               const uint8_t *palette);

/*
 Clear the scrollback history buffer

 This removes all lines from the scrollback buffer, freeing memory.
 The visible screen content is preserved.

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_clear_scrollback(struct Chau7Terminal *term);

/*
 Set the scrollback buffer size (number of lines)

 This updates the maximum number of lines that can be stored in the scrollback buffer.
 If the new size is smaller than the current history, older lines will be discarded.

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_set_scrollback_size(struct Chau7Terminal *term, uint32_t lines);

/*
 Get the current display offset (scroll position in lines)

 Returns:
 - 0 if at the bottom (showing current output)
 - >0 if scrolled up (viewing history)

 This is useful for implementing smart scroll behavior: only auto-scroll
 to bottom if display_offset is 0.

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_display_offset(struct Chau7Terminal *term);

/*
 Get the current mouse mode as a bitfield.

 Returns a u32 with the following bits:
 - Bit 0 (0x01): MOUSE_REPORT_CLICK - Mouse mode 1000 (report button press/release)
 - Bit 1 (0x02): MOUSE_DRAG - Mouse mode 1002 (also report motion while button down)
 - Bit 2 (0x04): MOUSE_MOTION - Mouse mode 1003 (report all motion)
 - Bit 3 (0x08): FOCUS_IN_OUT - Focus in/out reporting (mode 1004)
 - Bit 4 (0x10): SGR_MOUSE - Mouse mode 1006 (use SGR encoding for coordinates >223)

 To check if any mouse reporting is active, check if (result & 0x07) != 0.
 To check if SGR mode should be used, check if (result & 0x10) != 0.

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_mouse_mode(struct Chau7Terminal *term);

/*
 Check if bracketed paste mode is enabled

 Returns true if the terminal has bracketed paste mode enabled.
 This is typically set by programs like vim, zsh, or any readline-based
 application via the escape sequence ESC[?2004h.

 When enabled, pasted text should be wrapped with ESC[200~ and ESC[201~
 to distinguish it from typed input.

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_bracketed_paste_mode(struct Chau7Terminal *term);

/*
 Check if application cursor mode (DECCKM) is enabled

 Returns true if the terminal has application cursor mode enabled.
 This is typically set by programs like vim, less, tmux via the escape
 sequence ESC[?1h (DECCKM - DEC Cursor Key Mode).

 When enabled, arrow keys should send SS3 sequences (ESC O A/B/C/D)
 instead of CSI sequences (ESC [ A/B/C/D).

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_application_cursor_mode(struct Chau7Terminal *term);

/*
 Check if a bell event has occurred since the last check

 Returns true if a bell (BEL, 0x07) was received by the terminal since
 the last call to this function. The flag is automatically cleared.

 This allows Swift to poll for bell events and trigger audio/visual feedback.

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_check_bell(struct Chau7Terminal *term);

/*
 Get the current mouse mode as a bitmask

 Returns a u32 representing which mouse modes are active:
 - Bit 0 (1): MOUSE_REPORT_CLICK - Basic mouse click reporting (mode 1000)
 - Bit 1 (2): MOUSE_DRAG - Mouse drag reporting (mode 1002)
 - Bit 2 (4): MOUSE_MOTION - All mouse motion reporting (mode 1003)
 - Bit 3 (8): FOCUS_IN_OUT - Focus in/out reporting (mode 1004)
 - Bit 4 (16): SGR_MOUSE - SGR extended coordinates (mode 1006)

 Returns 0 if no mouse modes are active or if term is null.

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_get_mouse_mode(struct Chau7Terminal *term);

/*
 Check if any mouse tracking mode is active (click, drag, or motion reporting)

 This is a convenience function that returns true if any of the mouse
 tracking modes (MOUSE_REPORT_CLICK, MOUSE_DRAG, or MOUSE_MOTION) are enabled.
 These modes indicate that mouse events should be reported to the running
 application (e.g., vim, tmux, htop) rather than handled by the terminal.

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_mouse_reporting_active(struct Chau7Terminal *term);

/*
 Get the shell process ID

 Returns the PID of the shell process running in this terminal.
 This is useful for dev server monitoring which needs to find child processes.
 Returns 0 if the terminal is invalid or PID is not available.

 # Safety
 - `term` must be a valid pointer
 */
uint64_t chau7_terminal_get_shell_pid(struct Chau7Terminal *term);

/*
 Get a comprehensive debug state snapshot

 Returns a pointer to a DebugState struct containing terminal state and metrics.
 The caller must free this with `chau7_terminal_free_debug_state`.

 # Safety
 - `term` must be a valid pointer
 - The returned pointer must be freed with `chau7_terminal_free_debug_state`
 */
struct DebugState *chau7_terminal_get_debug_state(struct Chau7Terminal *term);

/*
 Free a debug state returned by `chau7_terminal_get_debug_state`

 # Safety
 - `state` must be a valid pointer returned by `chau7_terminal_get_debug_state`
 - The pointer must not be used after this call
 */
void chau7_terminal_free_debug_state(struct DebugState *state);

/*
 Get the full buffer text (visible + scrollback) for debugging

 Returns a null-terminated string containing the entire terminal buffer.
 The caller must free this with `chau7_terminal_free_string`.

 # Safety
 - `term` must be a valid pointer
 - The returned pointer must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_full_buffer_text(struct Chau7Terminal *term);

/*
 Reset performance metrics

 Clears all performance counters (poll count, timing, etc.)

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_reset_metrics(struct Chau7Terminal *term);

/*
 Get current activity level (0-100)

 Returns the terminal's current activity level as a percentage.
 100 = very active (lots of output), 0 = completely idle

 # Safety
 - `term` must be a valid pointer
 */
uint8_t chau7_terminal_activity_level(struct Chau7Terminal *term);

/*
 Check if poll should be skipped (power saving)

 Returns true if the terminal has been idle long enough that the next
 poll cycle can be skipped to save power. Use this for adaptive polling.

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_should_skip_poll(struct Chau7Terminal *term);

/*
 Get count of dirty rows (for partial update optimization)

 Returns the number of rows that have changed since the last clear.
 Use this to determine if a partial or full update is needed.

 # Safety
 - `term` must be a valid pointer
 */
uint32_t chau7_terminal_dirty_row_count(struct Chau7Terminal *term);

/*
 Clear dirty row tracking

 Call this after syncing the grid to Swift to reset the dirty state.

 # Safety
 - `term` must be a valid pointer
 */
void chau7_terminal_clear_dirty_rows(struct Chau7Terminal *term);

/*
 Get pending title change from OSC 0/1/2 escape sequences

 Returns the pending title as a C string, or null if no title change pending.
 The caller must free this string with `chau7_terminal_free_string`.
 After this call, the pending title is cleared.

 # Safety
 - `term` must be a valid pointer
 - The returned string must be freed with `chau7_terminal_free_string`
 */
char *chau7_terminal_get_pending_title(struct Chau7Terminal *term);

/*
 Get pending child exit code

 Returns the exit code if the child process has exited, or -1 if still running.
 After this call, the pending exit code is cleared.
 Note: Exit code is only set when alacritty_terminal fires the ChildExit event.

 # Safety
 - `term` must be a valid pointer
 */
int32_t chau7_terminal_get_pending_exit_code(struct Chau7Terminal *term);

/*
 Check if the PTY has closed (Exit event received)

 Returns true if the PTY has closed. This can happen when:
 - The shell exits naturally (exit command)
 - The shell process crashes
 - The terminal connection is terminated

 # Safety
 - `term` must be a valid pointer
 */
bool chau7_terminal_is_pty_closed(struct Chau7Terminal *term);

#endif  /* CHAU7_TERMINAL_H */
