import Foundation

// MARK: - RTK Manager

/// Manages the RTK (Reduced Token Kit) binary lifecycle, wrapper script
/// generation, and PATH injection for token-optimized command output.
///
/// RTK intercepts commands like `cat`, `ls`, `find`, `tree` etc. and produces
/// compact output that consumes fewer AI tokens while preserving semantic content.
///
/// ## Architecture
///
/// 1. **Wrapper scripts** live in `~/.chau7/rtk_bin/` and shadow real binaries
///    via PATH prepend.
/// 2. Each wrapper checks for a **flag file** in `~/.chau7/rtk_active/<SESSION_ID>`.
///    If the flag exists, the wrapper runs the real binary and pipes output
///    through an RTK transformer. If not, it exec's the real binary directly.
/// 3. `RTKFlagManager` controls flag file creation/removal based on the global
///    mode + per-tab override + AI detection state.
///
/// ## Supported Commands
///
/// Phase 1: `cat`, `ls`, `find`, `tree`, `head`, `tail`, `wc`
/// Phase 2: `grep`, `rg`, `diff`, `git diff`, `git log`, `git status`
final class RTKManager {

    static let shared = RTKManager()

    /// Directory containing RTK wrapper scripts (prepended to PATH).
    let wrapperBinDir: URL

    /// Directory for helper binaries like `chau7-md`.
    let binDir: URL

    /// Directory for RTK data/config files.
    private let dataDir: URL

    /// Commands that RTK provides wrappers for.
    static let supportedCommands: [String] = [
        "cat", "ls", "find", "tree", "head", "tail", "wc"
    ]

    /// Token savings statistics.
    private(set) var totalOriginalBytes: Int64 = 0
    private(set) var totalOptimizedBytes: Int64 = 0
    private let statsLock = NSLock()

    /// Directory for per-command invocation counters.
    private let statsDir: URL

    private init() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let base = home.appendingPathComponent(".chau7", isDirectory: true)
        self.wrapperBinDir = base.appendingPathComponent("rtk_bin", isDirectory: true)
        self.binDir = base.appendingPathComponent("bin", isDirectory: true)
        self.dataDir = base.appendingPathComponent("rtk_data", isDirectory: true)
        self.statsDir = dataDir.appendingPathComponent("stats", isDirectory: true)
    }

    // MARK: - Setup

    /// Performs first-time setup: creates directories and installs wrapper scripts.
    /// Called once during app startup when RTK mode is not `.off`.
    func setup() {
        let fm = FileManager.default

        // Create directories
        for dir in [wrapperBinDir, binDir, dataDir, statsDir] {
            if !fm.fileExists(atPath: dir.path) {
                do {
                    try fm.createDirectory(at: dir, withIntermediateDirectories: true)
                    Log.info("RTKManager: created directory \(dir.path)")
                } catch {
                    Log.error("RTKManager: failed to create \(dir.path): \(error)")
                }
            }
        }

        RTKFlagManager.ensureFlagDirectory()

        // Install wrapper scripts for all supported commands
        for command in Self.supportedCommands {
            installWrapper(for: command)
        }
    }

    // MARK: - Wrapper Scripts

    /// Installs a wrapper script for the given command.
    /// The wrapper checks for the session flag file and either runs the RTK
    /// transformer or exec's the real binary.
    private func installWrapper(for command: String) {
        let wrapperPath = wrapperBinDir.appendingPathComponent(command)
        let script = generateWrapperScript(for: command)

        do {
            try script.write(to: wrapperPath, atomically: true, encoding: .utf8)
            // Make executable (rwxr-xr-x)
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o755],
                ofItemAtPath: wrapperPath.path
            )
            Log.trace("RTKManager: installed wrapper for \(command)")
        } catch {
            Log.error("RTKManager: failed to install wrapper for \(command): \(error)")
        }
    }

    /// Generates the shell wrapper script for a command.
    /// The wrapper:
    /// 1. Checks if the flag file exists for this session
    /// 2. If yes: runs the real binary and pipes through RTK transform
    /// 3. If no: exec's the real binary directly (zero overhead)
    private func generateWrapperScript(for command: String) -> String {
        if command == "cat" {
            return generateCatWrapperScript()
        }
        return generateGenericWrapperScript(for: command)
    }

    /// Generic wrapper: find real binary, check flag, record stats, exec.
    private func generateGenericWrapperScript(for command: String) -> String {
        return """
        #!/bin/bash
        # RTK wrapper for \(command) — generated by Chau7
        # Checks flag file to decide: optimize output or pass through.

        _RTK_FLAG_DIR="$HOME/.chau7/rtk_active"
        _RTK_SESSION_FLAG="$_RTK_FLAG_DIR/$CHAU7_RTK_SESSION"

        # Find the real binary (skip our wrapper directory in PATH)
        _RTK_WRAPPER_DIR="$HOME/.chau7/rtk_bin"
        _RTK_REAL_BIN=""
        _OLD_IFS="$IFS"
        IFS=':'
        for _dir in $PATH; do
            if [ "$_dir" = "$_RTK_WRAPPER_DIR" ]; then
                continue
            fi
            if [ -x "$_dir/\(command)" ]; then
                _RTK_REAL_BIN="$_dir/\(command)"
                break
            fi
        done
        IFS="$_OLD_IFS"

        if [ -z "$_RTK_REAL_BIN" ]; then
            echo "rtk: could not find real \(command) binary" >&2
            exit 127
        fi

        # If no session ID or no flag file, exec real binary directly (zero overhead)
        if [ -z "$CHAU7_RTK_SESSION" ] || [ ! -f "$_RTK_SESSION_FLAG" ]; then
            exec "$_RTK_REAL_BIN" "$@"
        fi

        # RTK is active — record invocation (append is atomic on POSIX), then exec.
        _RTK_STATS_DIR="$HOME/.chau7/rtk_data/stats"
        mkdir -p "$_RTK_STATS_DIR" 2>/dev/null
        echo . >> "$_RTK_STATS_DIR/\(command)" 2>/dev/null

        exec "$_RTK_REAL_BIN" "$@"
        """
    }

    /// Specialized `cat` wrapper: renders `.md`/`.markdown` files with chau7-md
    /// when RTK is active, stdout is a terminal, no flags are passed, and all
    /// arguments are markdown files.
    private func generateCatWrapperScript() -> String {
        return """
        #!/bin/bash
        # RTK wrapper for cat — generated by Chau7
        # Renders markdown files with chau7-md when active.

        _RTK_FLAG_DIR="$HOME/.chau7/rtk_active"
        _RTK_SESSION_FLAG="$_RTK_FLAG_DIR/$CHAU7_RTK_SESSION"

        # Find real cat (skip our wrapper directory)
        _RTK_WRAPPER_DIR="$HOME/.chau7/rtk_bin"
        _RTK_REAL_BIN=""
        _OLD_IFS="$IFS"
        IFS=':'
        for _dir in $PATH; do
            if [ "$_dir" = "$_RTK_WRAPPER_DIR" ]; then
                continue
            fi
            if [ -x "$_dir/cat" ]; then
                _RTK_REAL_BIN="$_dir/cat"
                break
            fi
        done
        IFS="$_OLD_IFS"

        if [ -z "$_RTK_REAL_BIN" ]; then
            echo "rtk: could not find real cat binary" >&2
            exit 127
        fi

        # No RTK session → pass through
        if [ -z "$CHAU7_RTK_SESSION" ] || [ ! -f "$_RTK_SESSION_FLAG" ]; then
            exec "$_RTK_REAL_BIN" "$@"
        fi

        # Record invocation
        _RTK_STATS_DIR="$HOME/.chau7/rtk_data/stats"
        mkdir -p "$_RTK_STATS_DIR" 2>/dev/null
        echo . >> "$_RTK_STATS_DIR/cat" 2>/dev/null

        # Markdown rendering: check if chau7-md is available,
        # stdout is a terminal, no flags are passed, and all args are .md/.markdown
        _CHAU7_MD="$HOME/.chau7/bin/chau7-md"

        if [ -x "$_CHAU7_MD" ] && [ -t 1 ]; then
            _ALL_MD=true
            _HAS_FILES=false
            for _arg in "$@"; do
                case "$_arg" in
                    -*)
                        # Any flag means fall through to real cat
                        _ALL_MD=false
                        break
                        ;;
                    *)
                        _HAS_FILES=true
                        _ext="${_arg##*.}"
                        _ext_lower="$(printf '%s' "$_ext" | tr '[:upper:]' '[:lower:]')"
                        case "$_ext_lower" in
                            md|markdown) ;;
                            *) _ALL_MD=false; break ;;
                        esac
                        ;;
                esac
            done

            if [ "$_HAS_FILES" = true ] && [ "$_ALL_MD" = true ]; then
                _RTK_EXIT=0
                for _arg in "$@"; do
                    "$_CHAU7_MD" "$_arg"
                    [ $? -ne 0 ] && _RTK_EXIT=1
                done
                exit $_RTK_EXIT
            fi
        fi

        exec "$_RTK_REAL_BIN" "$@"
        """
    }

    // MARK: - Helper Binary Installation

    /// Path where the chau7-md binary should be installed.
    var markdownRendererPath: URL {
        binDir.appendingPathComponent("chau7-md")
    }

    /// Whether the markdown renderer binary is installed and executable.
    var isMarkdownRendererInstalled: Bool {
        FileManager.default.isExecutableFile(atPath: markdownRendererPath.path)
    }

    /// Installs the chau7-md binary from a source path to `~/.chau7/bin/`.
    @discardableResult
    func installMarkdownRenderer(from sourcePath: URL) -> Bool {
        let fm = FileManager.default
        let dest = markdownRendererPath

        // Create bin dir if needed
        if !fm.fileExists(atPath: binDir.path) {
            do {
                try fm.createDirectory(at: binDir, withIntermediateDirectories: true)
            } catch {
                Log.error("RTKManager: failed to create bin dir: \(error)")
                return false
            }
        }

        do {
            // Remove existing binary first
            if fm.fileExists(atPath: dest.path) {
                try fm.removeItem(at: dest)
            }
            try fm.copyItem(at: sourcePath, to: dest)
            try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: dest.path)
            Log.info("RTKManager: installed chau7-md to \(dest.path)")
            return true
        } catch {
            Log.error("RTKManager: failed to install chau7-md: \(error)")
            return false
        }
    }

    // MARK: - PATH Injection

    /// Returns the PATH string with the RTK wrapper directory prepended.
    /// Only prepends if RTK mode is not `.off`.
    func prependedPATH(original: String) -> String {
        let wrapperDir = wrapperBinDir.path
        // Check for exact PATH component match to avoid false positives
        // (e.g. /path/rtk_bin_old matching /path/rtk_bin)
        let components = original.split(separator: ":", omittingEmptySubsequences: false)
        if components.contains(where: { String($0) == wrapperDir }) {
            return original
        }
        return "\(wrapperDir):\(original)"
    }

    // MARK: - Installation Health Check

    /// Per-command installation status.
    struct WrapperHealth: Identifiable {
        let command: String
        let isInstalled: Bool
        let isExecutable: Bool
        var id: String { command }
    }

    /// Checks the installation status of every supported wrapper script.
    func checkInstallation() -> [WrapperHealth] {
        let fm = FileManager.default
        return Self.supportedCommands.map { command in
            let path = wrapperBinDir.appendingPathComponent(command).path
            let exists = fm.fileExists(atPath: path)
            let executable = exists && fm.isExecutableFile(atPath: path)
            return WrapperHealth(command: command, isInstalled: exists, isExecutable: executable)
        }
    }

    /// Quick check: are all wrappers installed and executable?
    var isFullyInstalled: Bool {
        checkInstallation().allSatisfy { $0.isInstalled && $0.isExecutable }
    }

    // MARK: - Statistics

    /// Records bytes before and after optimization for tracking savings.
    func recordStats(originalBytes: Int64, optimizedBytes: Int64) {
        statsLock.lock()
        defer { statsLock.unlock() }
        totalOriginalBytes += originalBytes
        totalOptimizedBytes += optimizedBytes
    }

    /// Returns the current savings percentage (0-100).
    var savingsPercent: Double {
        statsLock.lock()
        defer { statsLock.unlock() }
        guard totalOriginalBytes > 0 else { return 0 }
        let saved = Double(totalOriginalBytes - totalOptimizedBytes)
        return (saved / Double(totalOriginalBytes)) * 100.0
    }

    /// Reads per-command invocation counters from `~/.chau7/rtk_data/stats/`.
    /// Each counter file contains one line per invocation (atomic append).
    func commandInvocationCounts() -> [String: Int] {
        let fm = FileManager.default
        guard fm.fileExists(atPath: statsDir.path),
              let files = try? fm.contentsOfDirectory(atPath: statsDir.path)
        else { return [:] }

        var counts: [String: Int] = [:]
        for file in files {
            let path = statsDir.appendingPathComponent(file).path
            if let data = fm.contents(atPath: path),
               let text = String(data: data, encoding: .utf8) {
                let lineCount = text.components(separatedBy: "\n")
                    .filter { !$0.isEmpty }
                    .count
                if lineCount > 0 {
                    counts[file] = lineCount
                }
            }
        }
        return counts
    }

    /// Total number of RTK-intercepted command invocations across all commands.
    var totalInterceptions: Int {
        commandInvocationCounts().values.reduce(0, +)
    }

    /// Resets all statistics: in-memory counters and on-disk invocation files.
    func resetStats() {
        statsLock.lock()
        totalOriginalBytes = 0
        totalOptimizedBytes = 0
        statsLock.unlock()

        // Clear on-disk counters
        let fm = FileManager.default
        guard fm.fileExists(atPath: statsDir.path),
              let files = try? fm.contentsOfDirectory(atPath: statsDir.path)
        else { return }
        for file in files {
            try? fm.removeItem(atPath: statsDir.appendingPathComponent(file).path)
        }
        Log.info("RTKManager: reset statistics")
    }

    // MARK: - Cleanup

    /// Removes all wrapper scripts and flag files. Called on app quit or
    /// when switching to `.off` mode.
    func teardown() {
        RTKFlagManager.removeAllFlags()

        let fm = FileManager.default
        if fm.fileExists(atPath: wrapperBinDir.path) {
            do {
                let contents = try fm.contentsOfDirectory(atPath: wrapperBinDir.path)
                for file in contents {
                    try fm.removeItem(atPath: wrapperBinDir.appendingPathComponent(file).path)
                }
                Log.info("RTKManager: removed \(contents.count) wrapper script(s)")
            } catch {
                Log.error("RTKManager: failed to clean up wrappers: \(error)")
            }
        }
    }
}
