import Foundation

// MARK: - RTK Manager

/// Manages the RTK (Reduced Token Kit) binary lifecycle, wrapper script
/// generation, and PATH injection for token-optimized command output.
///
/// RTK intercepts commands like `cat`, `ls`, `find`, `tree` etc. and produces
/// compact output that consumes fewer AI tokens while preserving semantic content.
///
/// ## Architecture
///
/// 1. **Wrapper scripts** live in `~/.chau7/rtk_bin/` and shadow real binaries
///    via PATH prepend.
/// 2. Each wrapper checks for a **flag file** in `~/.chau7/rtk_active/<SESSION_ID>`.
///    If the flag exists, the wrapper runs the real binary and pipes output
///    through an RTK transformer. If not, it exec's the real binary directly.
/// 3. `RTKFlagManager` controls flag file creation/removal based on the global
///    mode + per-tab override + AI detection state.
///
/// ## Supported Commands
///
/// Phase 1: `cat`, `ls`, `find`, `tree`, `head`, `tail`, `wc`
/// Phase 2: `grep`, `rg`, `diff`, `git diff`, `git log`, `git status`
final class RTKManager {

    static let shared = RTKManager()

    /// Directory containing RTK wrapper scripts (prepended to PATH).
    let wrapperBinDir: URL

    /// Directory for RTK data/config files.
    private let dataDir: URL

    /// Commands that RTK provides wrappers for.
    static let supportedCommands: [String] = [
        "cat", "ls", "find", "tree", "head", "tail", "wc"
    ]

    /// Token savings statistics.
    private(set) var totalOriginalBytes: Int64 = 0
    private(set) var totalOptimizedBytes: Int64 = 0
    private let statsLock = NSLock()

    private init() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let base = home.appendingPathComponent(".chau7", isDirectory: true)
        self.wrapperBinDir = base.appendingPathComponent("rtk_bin", isDirectory: true)
        self.dataDir = base.appendingPathComponent("rtk_data", isDirectory: true)
    }

    // MARK: - Setup

    /// Performs first-time setup: creates directories and installs wrapper scripts.
    /// Called once during app startup when RTK mode is not `.off`.
    func setup() {
        let fm = FileManager.default

        // Create directories
        for dir in [wrapperBinDir, dataDir] {
            if !fm.fileExists(atPath: dir.path) {
                do {
                    try fm.createDirectory(at: dir, withIntermediateDirectories: true)
                    Log.info("RTKManager: created directory \(dir.path)")
                } catch {
                    Log.error("RTKManager: failed to create \(dir.path): \(error)")
                }
            }
        }

        RTKFlagManager.ensureFlagDirectory()

        // Install wrapper scripts for all supported commands
        for command in Self.supportedCommands {
            installWrapper(for: command)
        }
    }

    // MARK: - Wrapper Scripts

    /// Installs a wrapper script for the given command.
    /// The wrapper checks for the session flag file and either runs the RTK
    /// transformer or exec's the real binary.
    private func installWrapper(for command: String) {
        let wrapperPath = wrapperBinDir.appendingPathComponent(command)
        let script = generateWrapperScript(for: command)

        do {
            try script.write(to: wrapperPath, atomically: true, encoding: .utf8)
            // Make executable (rwxr-xr-x)
            try FileManager.default.setAttributes(
                [.posixPermissions: 0o755],
                ofItemAtPath: wrapperPath.path
            )
            Log.trace("RTKManager: installed wrapper for \(command)")
        } catch {
            Log.error("RTKManager: failed to install wrapper for \(command): \(error)")
        }
    }

    /// Generates the shell wrapper script for a command.
    /// The wrapper:
    /// 1. Checks if the flag file exists for this session
    /// 2. If yes: runs the real binary and pipes through RTK transform
    /// 3. If no: exec's the real binary directly (zero overhead)
    private func generateWrapperScript(for command: String) -> String {
        // Find the real binary path by searching PATH excluding our wrapper dir
        // This ensures we don't create a recursive wrapper
        return """
        #!/bin/bash
        # RTK wrapper for \(command) — generated by Chau7
        # Checks flag file to decide: optimize output or pass through.

        _RTK_FLAG_DIR="$HOME/.chau7/rtk_active"
        _RTK_SESSION_FLAG="$_RTK_FLAG_DIR/$CHAU7_SESSION_ID"

        # Find the real binary (skip our wrapper directory in PATH)
        _RTK_WRAPPER_DIR="$HOME/.chau7/rtk_bin"
        _RTK_REAL_BIN=""
        _OLD_IFS="$IFS"
        IFS=':'
        for _dir in $PATH; do
            if [ "$_dir" = "$_RTK_WRAPPER_DIR" ]; then
                continue
            fi
            if [ -x "$_dir/\(command)" ]; then
                _RTK_REAL_BIN="$_dir/\(command)"
                break
            fi
        done
        IFS="$_OLD_IFS"

        if [ -z "$_RTK_REAL_BIN" ]; then
            echo "rtk: could not find real \(command) binary" >&2
            exit 127
        fi

        # If no session ID or no flag file, exec real binary directly (zero overhead)
        if [ -z "$CHAU7_SESSION_ID" ] || [ ! -f "$_RTK_SESSION_FLAG" ]; then
            exec "$_RTK_REAL_BIN" "$@"
        fi

        # RTK is active — run real binary and apply token optimization
        # For now, pass through with a compact header comment
        _RTK_OUTPUT=$("$_RTK_REAL_BIN" "$@" 2>&1)
        _RTK_EXIT=$?

        if [ $_RTK_EXIT -eq 0 ]; then
            echo "$_RTK_OUTPUT"
        else
            echo "$_RTK_OUTPUT"
            exit $_RTK_EXIT
        fi
        """
    }

    // MARK: - PATH Injection

    /// Returns the PATH string with the RTK wrapper directory prepended.
    /// Only prepends if RTK mode is not `.off`.
    func prependedPATH(original: String) -> String {
        let wrapperDir = wrapperBinDir.path
        // Don't add if already present
        if original.contains(wrapperDir) {
            return original
        }
        return "\(wrapperDir):\(original)"
    }

    // MARK: - Statistics

    /// Records bytes before and after optimization for tracking savings.
    func recordStats(originalBytes: Int64, optimizedBytes: Int64) {
        statsLock.lock()
        defer { statsLock.unlock() }
        totalOriginalBytes += originalBytes
        totalOptimizedBytes += optimizedBytes
    }

    /// Returns the current savings percentage (0-100).
    var savingsPercent: Double {
        statsLock.lock()
        defer { statsLock.unlock() }
        guard totalOriginalBytes > 0 else { return 0 }
        let saved = Double(totalOriginalBytes - totalOptimizedBytes)
        return (saved / Double(totalOriginalBytes)) * 100.0
    }

    /// Resets statistics counters.
    func resetStats() {
        statsLock.lock()
        defer { statsLock.unlock() }
        totalOriginalBytes = 0
        totalOptimizedBytes = 0
    }

    // MARK: - Cleanup

    /// Removes all wrapper scripts and flag files. Called on app quit or
    /// when switching to `.off` mode.
    func teardown() {
        RTKFlagManager.removeAllFlags()

        let fm = FileManager.default
        if fm.fileExists(atPath: wrapperBinDir.path) {
            do {
                let contents = try fm.contentsOfDirectory(atPath: wrapperBinDir.path)
                for file in contents {
                    try fm.removeItem(atPath: wrapperBinDir.appendingPathComponent(file).path)
                }
                Log.info("RTKManager: removed \(contents.count) wrapper script(s)")
            } catch {
                Log.error("RTKManager: failed to clean up wrappers: \(error)")
            }
        }
    }
}
